services:
  manga-reader:
    image: python:3.11-slim
    container_name: manga-reader
    restart: unless-stopped
    
    # Run the main manager script
    command: python /app/manager.py
    
    # Port mapping
    ports:
      - "9008:9008"
    
    # Volume mounts
    volumes:
      # Mount all Python scripts
      - /mnt/nas_share/Containers/mangareader/manager.py:/app/manager.py:ro
      - /mnt/nas_share/Containers/mangareader/config.py:/app/config.py:ro
      - /mnt/nas_share/Containers/mangareader/database.py:/app/database.py:ro
      - /mnt/nas_share/Containers/mangareader/mangarequesthandler.py:/app/mangarequesthandler.py:ro
      
      # Mount the manga directory (read-only for safety)
      - /mnt/nas_share/Media/Manga:/mnt/nas_share/Media/Manga:ro
      
      # Mount the database directory (read-write for database file)
      - /mnt/nas_share/Containers/mangareader:/mnt/nas_share/Containers/mangareader:rw
    
    # Working directory
    working_dir: /app
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Pacific/Auckland  # Set to your timezone
      - DATABASE_FILE=/mnt/nas_share/Containers/mangareader/manga.db
    
    # Network mode
    network_mode: bridge
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:9008\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
